#ifndef _CONFIG_CAMERA_H_
#define _CONFIG_CAMERA_H_

/*==CAPTURE PARAMS==*/
#define N_CAPTURE 1

/*==WINDOW FLAGS BEGIN==*/
#define DISPLAY_MAIN_WINDOW 1
#define DISPLAY_BALL_MASK_WINDOW 1
#define DISPLAY (DISPLAY_MAIN_WINDOW | DISPLAY_BALL_MASK_WINDOW)
/*==WINDOW FLAGS END*/

/*==WINDOWS CONF BEGIN==*/
#if DISPLAY
    #if DISPLAY_MAIN_WINDOW
        #define NAME_MAIN_WINDOW "MAIN"
    #endif 

    #if DISPLAY_BALL_MASK_WINDOW
        #define NAME_BALL_MASK_WINDOW "BALL_MASK"
    #endif
#endif

#define WINDOW_SIZE_WIDTH 640
#define WINDOW_SIZE_HEIGHT 480
/*==WINDOWS CONF END==*/

/*==CAMERA BALL FILTER BEGIN==*/
#define BALL_HSV_MIN_LIGHT_LEVEL 40
#define BALL_HSV_MAX_LIGHT_LEVEL 255

#define BALL_HSV_LEFT_RANGE_BEGIN 0
#define BALL_HSV_LEFT_RANGE_END 15

#define BALL_HSV_RIGHT_RANGE_BEGIN 160
#define BALL_HSV_RIGHT_RANGE_END 180

#define BALL_KERNEL_SIZE 4
/*==CAMERA BALL FILTER END==*/

/*==CAMERA ROBOT FILTER BEGIN==*/
#define ROBOT_HSV_MIN_LIGHT_LEVEL 40
#define ROBOT_HSV_MAX_LIGHT_LEVEL 255

#define ROBOT_HSV_RANGE_BEGIN 40
#define ROBOT_HSV_RANGE_END 70

#define ROBOT_KERNEL_SIZE 4
/*==CAMERA ROBOT FILTER END==*/

/*==CAMERA CALIBRATION BEGIN==*/
#define PIXEL_TO_M 1.f

#define X_START_FIELD 0
#define X_FINISH_FIELD 10
#define Y_START_FIELD 0
#define Y_FINISH_FIELD 10

/*==CAMERA CALIBRATION BEGIN==*/    

#endif // !_CONFIG_CAMERA_H_