#ifndef _CONFIG_CAMERA_H_
#define _CONFIG_CAMERA_H_

/*==CAPTURE PARAMS==*/
#define N_CAPTURE 1

/*==WINDOW FLAGS BEGIN==*/
#define DISPLAY_MAIN_WINDOW 1
#define DISPLAY_BALL_MASK_WINDOW 1
#define DISPLAY (DISPLAY_MAIN_WINDOW | DISPLAY_BALL_MASK_WINDOW)
/*==WINDOW FLAGS END*/

/*==WINDOWS BEGIN==*/
#if DISPLAY
    #if DISPLAY_MAIN_WINDOW
        #define NAME_MAIN_WINDOW "MAIN"
    #endif 

    #if DISPLAY_BALL_MASK_WINDOW
        #define NAME_BALL_MASK_WINDOW "BALL_MASK"
    #endif
#endif
/*==WINDOWS END==*/

/*==CAMERA FILTER BEGIN==*/
#define HSV_MAX_LIGHT_LEVEL 255
#define HSV_MIN_LIGHT_LEVEL 40

#define HSV_LEFT_RANGE_RED_BEGIN 0
#define HSV_LEFT_RANGE_RED_END 15

#define HSV_RIGHT_RANGE_RED_BEGIN 160
#define HSV_RIGHT_RANGE_RED_END 180

#define KERNEL_SIZE 4
/*==CAMERA FILTER END==*/

/*==CAMERA CALIBRATION BEGIN==*/
#define PIXEL_TO_M 1.f
#define DELAY_AFTER_SET_LINE_MS 100
/*==CAMERA CALIBRATION BEGIN==*/    

#endif // !_CONFIG_CAMERA_H_