#ifndef _CONFIG_CAMERA_H_
#define _CONFIG_CAMERA_H_

/*==CAPTURE PARAMS==*/
#define N_CAPTURE 0

/*==WINDOW FLAGS BEGIN==*/
#define CALC_CAM 1

#define DISPLAY_MAIN_WINDOW (1 && CALC_CAM)
#define DISPLAY_BALL_MASK_WINDOW (0 && CALC_CAM)
#define DISPLAY_ROBOT_MASK_WINDOW (0 && CALC_CAM)
#define DISPLAY_FIELD_WINDOW (1 && CALC_CAM)

#define DISPLAY ((DISPLAY_MAIN_WINDOW || DISPLAY_BALL_MASK_WINDOW || DISPLAY_ROBOT_MASK_WINDOW || DISPLAY_FIELD_WINDOW) && CALC_CAM)
/*==WINDOW FLAGS END*/

/*==WINDOWS CONF BEGIN==*/
#if DISPLAY
    #if DISPLAY_MAIN_WINDOW
        #define NAME_MAIN_WINDOW "MAIN"
    #endif 

    #if DISPLAY_BALL_MASK_WINDOW
        #define NAME_BALL_MASK_WINDOW "BALL_MASK"
    #endif

    #if DISPLAY_ROBOT_MASK_WINDOW
        #define NAME_ROBOT_MASK_WINDOW "ROBOT_MASK"
    #endif

    #if DISPLAY_FIELD_WINDOW
        #define NAME_FIELD_WINDOW "FIELD"
    #endif
#endif

#define WINDOW_SIZE_WIDTH (640 / 1)
#define WINDOW_SIZE_HEIGHT (480 / 1) 
/*==WINDOWS CONF END==*/

/*==CAMERA BALL FILTER BEGIN==*/
#define BALL_HSV_MIN_LIGHT_LEVEL 100
#define BALL_HSV_MAX_LIGHT_LEVEL 255

// red
#define BALL_HSV_LEFT_RANGE_BEGIN 0
#define BALL_HSV_LEFT_RANGE_END 15

#define BALL_HSV_RIGHT_RANGE_BEGIN 160
#define BALL_HSV_RIGHT_RANGE_END 180

#define BALL_KERNEL_SIZE 2
/*==CAMERA BALL FILTER END==*/

/*==CAMERA ROBOT FILTER BEGIN==*/
#define ROBOT_HSV_MIN_LIGHT_LEVEL 120
#define ROBOT_HSV_MAX_LIGHT_LEVEL 255

// blue
#define ROBOT_HSV_RANGE_BEGIN 85
#define ROBOT_HSV_RANGE_END 110

#define ROBOT_KERNEL_SIZE 2
/*==CAMERA ROBOT FILTER END==*/

/*==CAMERA CALIBRATION BEGIN==*/
/*==SIDE 1 BEGIN==*/
#define X_1_FIELD 556
#define Y_1_FIELD 478

#define X_2_FIELD 63
#define Y_2_FIELD 478

#define X_3_FIELD 55
#define Y_3_FIELD 20

#define X_4_FIELD 553
#define Y_4_FIELD 12
/*==SIDE 1 END==*/

/*==SIDE 2 BEGIN==*/
// #define X_1_FIELD 595
// #define Y_1_FIELD 458

// #define X_2_FIELD 112
// #define Y_2_FIELD 451

// #define X_3_FIELD 97
// #define Y_3_FIELD 28

// #define X_4_FIELD 600
// #define Y_4_FIELD 15
/*==SIDE 2 END==*/

#define X_START_RULER 505   
#define Y_START_RULER 0

#define X_END_RULER 640
#define Y_END_RULER 0

#define RULER_VALUE_SM 30.f 

#define SM_TO_PIXEL (RULER_VALUE_SM / (X_END_RULER - X_START_RULER))
#define SM_BEFORE_HIT 20
/*==CAMERA CALIBRATION BEGIN==*/    

#endif // !_CONFIG_CAMERA_H_