#ifndef _CONFIG_H_
#define _CONFIG_H_

/*==PROTOCOL FOR COMMUNICATION BEGIN==*/
/* PROTOCOL: |DATA|POST| */
#define DATA_BYTES_VALUE 1
#define PRE_BYTES_VALUE 1
#define POST_BYTES_VALUE 1
#define ID_BYTES_VALUE 0
#define CS_BYTES_VALUE 1
#define PACKET_BYTES_VALUE (DATA_BYTES_VALUE + PRE_BYTES_VALUE + POST_BYTES_VALUE + ID_BYTES_VALUE + CS_BYTES_VALUE)

#define PREAMBLE 0xAA
#define POSTAMBLE 0x55
/*==PROTOCOL FOR COMMUNICATION END*/

/*==UART FOR BLUETOOTH BEGIN==*/
#define BT_PORT 4
#define BT_BAUDRATE 115200
#define BT_DATASIZE 8
#define BT_PARITY 'N'
#define BT_STOPBIT 1
/*==UART FOR BLUETOOTH END==*/


#endif // !_CONFIG_H_