//g++ *.cpp -o main & main

/*==PROTOCOL FOR COMMUNICATION BEGIN==*/
/* PROTOCOL: |DATA|POST| */
#define DATA_BYTES_VALUE 8
#define PRE_BYTES_VALUE 2
#define ID_BYTES_VALUE 1
#define PACKET_BYTES_VALUE (PRE_BYTES_VALUE + DATA_BYTES_VALUE + ID_BYTES_VALUE)

#define POSTAMBLE 0xAA55
/*==PROTOCOL FOR COMMUNICATION END*/

/*==UART FOR BLUETOOTH BEGIN==*/
#define BT_PORT 5
#define BT_BAUDRATE 115200
#define BT_DATASIZE 8
#define BT_PARITY 'N'
#define BT_STOPBIT 1
/*==UART FOR BLUETOOTH END==*/